---
title: "Running Novae foundational model"
author: ""
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
abstract: >
This package takes an h5ad file with the gene count matrix and spatial coordinates as input, run Novae creating the Python environment automatically, and returns an annDataR object with the embeddings and domains (spatial clusters).
  
output:
  rmarkdown::html_document:
    highlight: pygments
    toc: true
vignette: >
  %\VignetteIndexEntry{Running Novae foundational model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---

```{r setup}
library(anndataR)
library(SpatialExperiment)
library(BiocFoundationGPU)

spe <- readRDS(
  system.file("extdata", "CosMx1k_MouseBrain1_100tx_100cl.rds", package = "BiocFoundationGPU")
)
```

Prepare h5ad file for Novae

```{r h5ad_creation}
spatialCoords(spe) |> as.data.frame() -> coords_df
colData(spe)$x_coord <- coords_df[, 1]
colData(spe)$y_coord <- coords_df[, 2]
reducedDim(spe, "spatial") <- as.matrix(spatialCoords(spe))

adata <- as_AnnData(spe)
colnames(adata$obsm$spatial) <- c("x_coord", "y_coord")

# write anndata to tempfile 
adata$write_h5ad(
  tp <- tempfile(fileext = ".h5ad"), 
  mode = "w"
)
```

Run Novae

```{r running_novae}
novae_data <- Run_novae(tp, accelerator = "cpu")
novae_data$obsm$novae_latent |> head()
```

Plotting spatial coordinates coloured by Novae's defined clusters (domains)

```{r plot_results}
library(ggplot2)

plot_df <- data.frame(
  x      = novae_data$obs$x_coord,
  y      = novae_data$obs$y_coord,
  domain = as.factor(novae_data$obs$novae_domains_7)
)

ggplot(plot_df, aes(x = x, y = y, color = domain)) +
  geom_point(size = 2, alpha = 0.8) +
  coord_fixed() +
  theme_classic() +
  labs(x = "x", y = "y", color = "Novae domain")
```
